CREATE DATABASE tgbot;
\c tgbot;

CREATE TABLE IF NOT EXISTS vacancies (
    id BIGINT,
    url TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS last (
    id BIGINT PRIMARY KEY,
    title TEXT NOT NULL,
    exp TEXT NOT NULL
);
