version: '3.8'

volumes:
  postgres:
    name: postgres
    driver: local
    driver_opts:
      device: /var/tmp/docker/postgresql
      o: bind
      type: none

services:
  db:
    build: ./PostgreSQL/
    image: db
    container_name: db
    env_file: ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

  app:
    depends_on:
      - db
    build: ./Bot/
    image: app
    container_name: app
    ports:
      - "8080:8080"
    restart: always
